Update Jenkinsfile for improved build process

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -1,74 +1,109 @@
 pipeline {
     agent {
         docker {
-            image 'maven:3.9-eclipse-temurin-17'
-            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
+            image 'maven:3.9.6-eclipse-temurin-17'
+            args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
         }
     }
+
     environment {
         JAVA_HOME = '/opt/java/openjdk'
         PATH = "${JAVA_HOME}/bin:${PATH}"
+        SONAR_URL = 'http://54.224.172.5:9000'
+        DOCKER_IMAGE = "amtulsaboor/ultimate-cicd:${BUILD_NUMBER}"
+        GIT_REPO_NAME = 'jenkins-end-to-end-implemntation'
+        GIT_USER_NAME = 'amtulsaboor'
     }
-    stages {
-        stage('Checkout') {
-            steps {
-                sh 'echo passed'
-               git branch: 'main', url: 'https://github.com/amtulsaboor/jenkins-end-to-end-implemntation.git'
 
-                                                             
+    stages {
+
+        stage('Checkout Code') {
+            steps {
+                echo 'Cloning GitHub Repository...'
+
+                git branch: 'main',
+                url: 'https://github.com/amtulsaboor/jenkins-end-to-end-implemntation.git'
             }
         }
+
         stage('Build and Test') {
             steps {
-                sh 'ls -ltr'                                                                                                                                                     
+                sh '''
+                    ls -ltr
+                    cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
+                    mvn clean install
+                '''
             }
         }
+
         stage('Static Code Analysis') {
-            environment {
-                SONAR_URL = "http://54.224.172.5:9000"                   
-            }                    
-            }
             steps {
                 withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
-                    sh '''  
-                      cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}
+
+                    sh '''
+                        cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
+
+                        mvn sonar:sonar \
+                        -Dsonar.projectKey=spring-boot-app \
+                        -Dsonar.host.url=${SONAR_URL} \
+                        -Dsonar.login=${SONAR_AUTH_TOKEN}
+                    '''
                 }
             }
         }
-        stage('Build and Push Docker Image') {
-            environment {
-                DOCKER_IMAGE = "amtulsaboor/ultimate-cicd:${BUILD_NUMBER}"
-            // DOCKERFILE_LOCATION = "java-maven-sonar-argocd-helm-k8s/spring-boot-app/Dockerfile"
-                REGISTRY_CREDENTIALS = credentials('docker-cred')
+
+        stage('Build Docker Image') {
+            steps {
+                sh '''
+                    cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
+
+                    docker build -t ${DOCKER_IMAGE} .
+                '''
             }
+        }
+
+        stage('Push Docker Image') {
             steps {
                 script {
-                    sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
-                    def dockerImage = docker.image("${DOCKER_IMAGE}")
-                    docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
-                dockerImage.push()
+
+                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
+
+                        sh "docker push ${DOCKER_IMAGE}"
                     }
                 }
             }
         }
-        stage('Update Deployment File') {
-            environment {
-                GIT_REPO_NAME = "Jenkins-end-to-end-implementation"
-                GIT_USER_NAME = "amtulsaboor"
-            }
+
+        stage('Update Kubernetes Deployment File') {
             steps {
+
                 withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
+
                     sh '''
-                        git config user.email "saboooorrrrrr@gmail.com"
-                        git config user.name "amtulsaboor"
-                        BUILD_NUMBER=${BUILD_NUMBER}
-                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+                        git config --global user.email "saboooorrrrrr@gmail.com"
+                        git config --global user.name "amtulsaboor"
+
+                        sed -i "s#replaceImageTag#${BUILD_NUMBER}#g" \
+                        java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+
                         git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                        git commit -m "Update deployment image to version ${BUILD_NUMBER}"
-                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
+
+                        git commit -m "Updated image tag to version ${BUILD_NUMBER}" || echo "No changes to commit"
+
+                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                     '''
                 }
             }
+        }
+    }
+
+    post {
+        success {
+            echo 'Pipeline executed successfully!'
+        }
+
+        failure {
+            echo 'Pipeline failed!'
         }
     }
 }
